# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
# What event triggers the check
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]  #here, multiple instances of Node.js can be taken into account, I've used only 18

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      
      # Check for Docker container is possible to build and run
      
      - name: Run Docker Compose
        run: docker-compose up --build
        
        #checking that neccessary files are present
        
      - name: Check Files
        run: |
          ls README.md
          ls cypress/e2e/login-register/*.spec.js | wc -l 
          
     # so on...
